/***************************************************************************f******************u************zz*******y**
 * File: EmployeePojo.java
 * Course materials (20W) CST 8277
 *
 * @author (original) Mike Norman
 * @author Adam Mohr 040669681
 * 
 */
package com.algonquincollege.cst8277.employeedirectory.model;

import static
com.algonquincollege.cst8277.employeedirectory.model.EmployeePojo.ALL_EMPLOYEES_QUERY_NAME;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.Version;

/**
 * Description: model for the employee object
 */
@Entity(name = "Employee")
@Table(name = "EMPLOYEE")
@Access(AccessType.PROPERTY)
@EntityListeners({EmployeePojoListener.class})
@NamedQueries(
    @NamedQuery(name=ALL_EMPLOYEES_QUERY_NAME, query = "select e from Employee e")
)
public class EmployeePojo implements Serializable {
    /** explicitly set serialVersionUID */
    private static final long serialVersionUID = 1L;

    /** explicitly name for query */
    public static final String ALL_EMPLOYEES_QUERY_NAME =
        "allEmployees";

    /** employee ID and Primary Key */
    protected int id;
    /** employee first name */
    protected String firstName;
    /** employee last name */
    protected String lastName;
    /** employee email */
    protected String email;
    /** employee title */
    protected String title;
    /** employee salary */
    protected Double salary;
    /** employee version in database */
    protected int version;
    /** toggle edit mode for view */
    @Transient
    protected boolean editable;
    /** employee date created on */
    protected LocalDateTime createdDate;
    /** employee date updated on */
    protected LocalDateTime updatedDate;

    /**
     * @return employee primary key ID automatically generated by database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getId() {
        return id;
    }
    
    /**
     * @param id new value for id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return the value for firstName
     */
    @Column(name = "FNAME")
    public String getFirstName() {
        return firstName;
    }
    /**
     * @param firstName new value for firstName
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * @return the value for lastName
     */
    @Column(name = "LNAME")
    public String getLastName() {
        return lastName;
    }
    /**
     * @param lastName new value for lastName
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * @return the value for email
     */
    public String getEmail() {
        return email;
    }
    /**
     * @param email new value for email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * @return the value for title
     */
    public String getTitle() {
        return title;
    }
    /**
     * @param title new value for title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * @return the value for salary
     */
    public Double getSalary() {
        return salary;
    }
    
    /**
     * @param salary new value for salary
     */
    public void setSalary(Double salary) {
        this.salary = salary;
    }

    /**
     * @return the value for version
     */
    @Version
    public int getVersion() {
        return version;
    }

    /**
     * @param version new value for version
     */
    public void setVersion(int version) {
        this.version = version;
    }
    
    /**
     * @param editable to toggle edit mode
     */
    public void setEditable(boolean editable) {
        this.editable = editable;
    }
    
    /**
     * @return editable to check if in edit mode for view
     */
    @Transient
    public boolean isEditable() {
        return editable;
    }

    /**
     * @return createdDate in database
     */
    @Column(name = "CREATED_DATE")
    public LocalDateTime getCreatedDate() {
        return createdDate;
    }
    
    /**
     * @param createdDate to set
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }
    
    /**
     * @return updatedDate in database
     */
    @Column(name = "UPDATED_DATE")
    public LocalDateTime getUpdatedDate() {
        return updatedDate;
    }
    
    /**
     * @param updatedDate to set
     */
    public void setUpdatedDate(LocalDateTime updatedDate) {
        this.updatedDate = updatedDate;
    }
    
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + id;
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof EmployeePojo)) {
            return false;
        }
        EmployeePojo other = (EmployeePojo) obj;
        if (id != other.id) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder
            .append("Employee [id=")
            .append(id)
            .append(", ");
        if (firstName != null) {
            builder
                .append("firstName=")
                .append(firstName)
                .append(", ");
        }
        if (lastName != null) {
            builder
                .append("lastName=")
                .append(lastName)
                .append(", ");
        }
        if (email != null) {
            builder
                .append("email=")
                .append(email)
                .append(", ");
        }
        if (salary != null) {
            builder
                .append("salary=")
                .append(salary)
                .append(", ");
        }
        if (title != null) {
            builder
                .append("title=")
                .append(title);
        }
        builder.append("]");
        return builder.toString();
    }

}